### PR TITLE
WIP: Personal page layout

### PR DESCRIPTION
**Pull request by lc-d**
Remember to pull new css rules from `hugo-trex-theme`.
_Note:_ Do not merge until WIP status is removed

### CODE REVIEW

**Comment by vecna** [comment]
@lc-d probably you forget to push the changes in 'hugo-trex-theme' because I only see one branch and the last commit is from privatemaker

**Comment by vecna** [comment]
Also, these checks are completed and are running on youtube.tracking.exposed https://github.com/tracking-exposed/yttrex/issues/13

**Comment by lc-d** [comment]
In commit  9510b8d I complete the TAG form trough the function `updateTags(e)`. It send via POST the `data` object, i.e. `{tag: "foo", password: "superfoo"}`.

Server respons is: `error: true
message: "Group name (tag parameter) shoulbe be a string with more than 1 char"`

**Comment by vecna** [comment]
A bug, the pagination do not scale well when there are a lot of entries: http://localhost:1313/personal/#41fJpKXZUKtmX5yoWA71nEsqc6T1XSKZdBG8CudMMT9n

**Comment by lc-d** [comment]
😄 I see. I'll fix it as soon as I can.

**Pull request merged**
